CodeSystem: DetailedSampleTypeCS
Id: miabis-detailed-samply-type-cs
Title: "DetailedSampleType"
Description: "Code system for the detailed sample type of a sample"
* #AmnioticFluid "Amniotic fluid"
* #AscitesFluid "ascites Fluid"
* #Bile "Bile"
* #BodyCavityFluid "Body cavity fluid"
* #Bone "Bone"
* #BoneMarrowAspirate "Bone marrow aspirate"
* #BoneMarrowPlasma "Bone marrow plasma"
* #BoneMarrowWhole "Bone marrow whole"
* #BreastMilk "Breast milk"
* #BronchLavage "Bronchoalveolar lavage"
* #BuffyCoat "Buffy coat"
* #CancerCellLine "Cancer cell lines"
* #CerebrospinalFluid "Cerebrospinal fluid"
* #CordBlood "Cord blood"
* #DentalPulp "Dental pulp"
* #DNA "DNA"
* #Embryo "Embryo"
* #EntireOrgan "Entire body Organ"
* #Faeces "Faeces"
* #FetalTissue "Fetal tissue"
* #Fibroblast "Fibroblast"
* #FoodSpecimen "Food specimen"
* #Gas "Gas exhaled (breath)"
* #GastricFluid "Gastric fluid"
* #Hair "Hair"
* #ImmortalizedCellLine "Immortalized cell line"
* #IsolatedMicrobe "Isolated microbes"
* #IsolatedExosome "Isolated or encriched exosomes"
* #IsolatedTumorCell "Isolated tumor cells(neoplastic cells)"
* #LiquidBiopsy "Liquid biopsy"
* #MenstrualBlood "Menstrual blood"
* #Nail "Nail"
* #NasalWashing "Nasal washing"
* #Organoid "Organoids"
* #Other "Other"
* #PericardialFluid "Pericardial fluid"
* #PBMC "Peripheral blood mononuclear cells"
* #Placenta "Placenta"
* #Plasma "Plasma"
* #PleuralFluid "Pleural fluid"
* #PostMortemTissue "Post-mortem tissue"
* #PrimaryCells "Primary cells"
* #Protein "Protein"
* #RedBloodCells "Red blood cells"
* #RNA "RNA"
* #Saliva "Saliva"
* #Semen "Semen"
* #Serum "Serum"
* #SpecimenEnvironment "Specimen from environment"
* #Sputum "Sputum"
* #StemCells "Stem cells and iPS cells"
* #Swab "Swab"
* #Sweat "Sweat"
* #SynovialFluid "Synovial fluid"
* #Tears "Tears"
* #Teeth "Teeth"
* #TissueFixed "Tissue (fixed)"
* #TissueFreshFrozen "Tissue (fresh frozen)"
* #UmbilicalCord "Umbilical cord"
* #Urine "Urine"
* #UrineSediment "Urine sediment"
* #VitreousFluid "Vitreous fluid"
* #WholeBlood "Whole blood"
* #WholeBloodDried "Whole blood dried(eg. Guthrie card)"
