
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Publish IG
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Install Jekyll
        run: sudo gem install jekyll

      - name: Install Sushi
        run:  sudo npm install -g fsh-sushi
        
      - name: check out Git repository
        uses: actions/checkout@v4
      
      
      - name: Build resources using Sushi
        run: |
          cd MiabisOnFHIR
          sushi build 

      - name: Move sushi output different folder
        run: |
          mkdir sushi-output 
          mkdir sushi-output/instances
          mkdir sushi-output/resources
          cp -R MiabisOnFHIR/fsh-generated/resources sushi-output
          cd sushi-output/resources
          mv *Instance.json ../instances

      - name: Download FHIR validator
        run: wget https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar -O validator_cli.jar

      - name: Run FHIR validator
        run: java -jar validator_cli.jar -ig sushi-output/resources -version 4.0.1 -extension http://example/org/ -allow-example-urls true  sushi-output/instances

      - name: Download Publisher
        run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -O publisher.jar
      - name: Run Publisher
        run: java -jar publisher.jar -ig MiabisOnFHIR/ig.ini

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: MiabisOnFHIR/output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4